site_name: Leaf Documentation

theme:
    name: material

#nav:
#    - Home  : index.md
#    - Admin : admin 
#    - Deploy:
#        - ABOUT : deploy
#        - APP   : deploy/app
#        - DB    : deploy/db
#        - FED   : deploy/fed
#        - SAML2 : deploy/saml2
#        - WEB   :
#            - APACHE: deploy/web/apache 
#            - CLIENT: deploy/web/client
#            - IIS   : deploy/web/iis





